development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Shubham@123
  pool:  5
  database: rails-intro

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Shubham@123
  pool:  5
  database: rails-intro

Production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Shubham@123
  pool:  5
  database: rails-intro

